"""add sync cursor and normalized sender/recipient fields

Revision ID: a4e974d393d1
Revises: 25e11f4098b5
Create Date: 2026-09-09 01:14:03.923918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e974d393d1'
down_revision: Union[str, None] = '25e11f4098b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_cursor', sa.String(length=255), nullable=True))

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sender_email', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('in_reply_to', sa.String(length=998), nullable=True))
        batch_op.add_column(sa.Column('references_header', sa.String(length=998), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_sender_email'), ['sender_email'], unique=False)
        batch_op.drop_column('sender')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(length=998), nullable=True))
        batch_op.drop_index(batch_op.f('ix_emails_sender_email'))
        batch_op.drop_column('references_header')
        batch_op.drop_column('in_reply_to')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('sender_name')

    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_column('sync_cursor')

    # ### end Alembic commands ###
